name: Publish Docker Image to GitHub Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: thakkaryash94/cockroach-backup
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
